apiVersion: v1
kind: Service
metadata:
  
  labels:
    app: app1
  name: app1s1
  namespace: trainer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app1
  type: NodePort

