apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: trainer
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memeory: "40M"
            cpu: "40m" 
          requests:
            memory: "20M"
            cpu: "20m"
