apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: trainer
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: 200M
    limits.cpu: "400m"
    limits.memory: 400M
    pods: 20
    services: 5
    persistentvolumeclaims: 5
    configmaps: 10
    secrets: 10
    replicationcontrollers: 5
    